@startuml arrancarSistema

skinparam linetype polyline

state arrancarSistema as "arrancarSistema()" {

    state " " as PresentandoPantallaInicial

    [*] -[#green]-> PresentandoPantallaInicial
    note on link
    <b>Jugador</b> solicita arrancar sistema
    end note

    PresentandoPantallaInicial -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta pantalla inicial
    <b>Sistema</b> permite solicitar:
    • iniciarPartida()
    end note
}

arrancarSistema -[#green]-> INACTIVO
note on link
sistema disponible
end note

@enduml
