@startuml rotarPieza

skinparam linetype polyline

EN_CURSO -[#green]-> rotarPieza
note on link
rotarPieza()
end note

state rotarPieza as "rotarPieza()" {

    state c1 <<choice>>

    [*] -[#green]-> c1
    note on link
    <b>Jugador</b> solicita rotar pieza
    end note

    c1 -[#green]-> [*]
    note on link
    rotación válida
    <b>Sistema</b> presenta pieza activa rotada
    end note

    c1 -[#red]-> [*]
    note on link
    rotación inválida
    (colisión o límite)
    <b>Sistema</b> presenta pieza activa
    sin rotación
    end note
}

state EN_CURSO_2 as "EN_CURSO"

rotarPieza -[#green]-> EN_CURSO_2
note on link
rotación realizada
end note

rotarPieza -[#red]-> EN_CURSO_2
note on link
rotación bloqueada
end note

@enduml
