@startuml

left to right direction

state Inactivo
state EnCurso
state Finalizado

[*] -> Inactivo : arrancarSistema()

Inactivo --> EnCurso : iniciarPartida()

EnCurso -> EnCurso : moverPieza()
EnCurso -> EnCurso : rotarPieza()
EnCurso -> EnCurso : alternarVelocidadCaida()

EnCurso -> EnCurso : iniciarPartida()

EnCurso --> Finalizado
EnCurso --> Inactivo : cancelarPartida()

Finalizado --> Inactivo : cancelarPartida()

Finalizado --> EnCurso : iniciarPartida()

@enduml