@startuml

left to right direction

state Inactivo
state EnCurso
state Finalizado

[*] -> Inactivo : arrancarSistema()

Inactivo --> EnCurso : iniciarPartida()

EnCurso -> EnCurso : moverPieza()
EnCurso -> EnCurso : rotarPieza()
EnCurso -> EnCurso : alternarVelocidadCaida()

EnCurso --> Finalizado
EnCurso --> Inactivo : reiniciarPartida()

Finalizado --> Inactivo : reiniciarPartida()

@enduml