@startuml

left to right direction

state Inactivo
state EnCurso
state Finalizado

[*] -> Inactivo

Inactivo --> EnCurso

EnCurso -> EnCurso : descenderPieza()

EnCurso --> Finalizado : descenderPieza [no hay espacio para nueva pieza]

Finalizado --> Inactivo

@enduml